/**
 * Prompt content. The design doc targets >=60 approved prompts per category for
 * public exposure; this set is in that range so games stay fresh (no repeats
 * within a game, low repetition across sessions). Curation principles:
 *   - mainstream / general-knowledge only (avoid niche),
 *   - NO category whose answers map directly to a single emoji (Foods 🍕,
 *     Countries 🇫🇷) — that makes the clue trivially the answer; Landmarks also
 *     skips single-emoji entries (Statue of Liberty 🗽, Mount Fuji 🗻, …),
 *   - answers are unique across all categories,
 *   - aliases must be a shorter form a player would TYPE for THIS exact title,
 *     never a broader franchise/character.
 *
 * Used by db/seedDatabase.ts (insert/reconcile) and ContentProvider (in-memory
 * fallback — the game runs on this set even without a seeded database).
 */

export interface SeedPrompt {
  answer: string;
  difficulty: number; // 1..5
  popularity: number; // 1..5
  aliases?: string[];
}

export interface SeedCategory {
  slug: string;
  name: string;
  description?: string;
  prompts: SeedPrompt[];
}

// Helper to keep entries terse: p(answer, difficulty, popularity, ...aliases)
const p = (answer: string, difficulty: number, popularity: number, ...aliases: string[]): SeedPrompt =>
  aliases.length ? { answer, difficulty, popularity, aliases } : { answer, difficulty, popularity };

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    slug: 'movies',
    name: 'Movies',
    description: 'Blockbuster films most people have seen.',
    prompts: [
      p('Titanic', 1, 5),
      p('Jurassic Park', 2, 5),
      p('The Matrix', 2, 5, 'Matrix'),
      p('Forrest Gump', 3, 5),
      p('Jaws', 2, 4),
      p('Frozen', 2, 5),
      p('The Lion King', 2, 5, 'Lion King'),
      p('Finding Nemo', 2, 5),
      p('Star Wars', 2, 5),
      p('The Godfather', 3, 4, 'Godfather'),
      p('Toy Story', 2, 5),
      p('Avatar', 2, 4),
      p('Shrek', 1, 5),
      p('Spider-Man', 2, 5, 'Spiderman'),
      p('The Wizard of Oz', 3, 4, 'Wizard of Oz'),
      p('Back to the Future', 3, 5),
      p('E.T.', 3, 4, 'ET', 'E.T. the Extra-Terrestrial'),
      p('Home Alone', 2, 5),
      p('Ghostbusters', 3, 4),
      p('Inception', 3, 4),
      p('Pirates of the Caribbean', 3, 4),
      p('The Avengers', 2, 5, 'Avengers'),
      p('Beauty and the Beast', 2, 4),
      p('The Dark Knight', 3, 4),
      p('Joker', 3, 4),
      p('Gladiator', 3, 4),
      p('The Shining', 3, 4),
      p('Alien', 3, 4),
      p('The Terminator', 3, 4, 'Terminator'),
      p('Top Gun', 3, 4),
      p('Mission Impossible', 3, 4),
      p('Indiana Jones', 3, 4),
      p('Despicable Me', 2, 5),
      p('Moana', 2, 5),
      p('Aladdin', 2, 5),
      p('The Little Mermaid', 2, 4, 'Little Mermaid'),
      p('Cinderella', 2, 5),
      p('Snow White', 2, 5),
      p('Ratatouille', 3, 4),
      p('WALL-E', 3, 4),
      p('Coco', 3, 4),
      p('Inside Out', 2, 5),
      p('Monsters Inc', 3, 4),
      p('Kung Fu Panda', 2, 4),
      p('The Incredibles', 2, 4, 'Incredibles'),
      p('Zootopia', 3, 4),
      p('Jumanji', 3, 4),
      p('Men in Black', 3, 4),
      p('Interstellar', 3, 4),
      p('Mad Max', 3, 4),
      p('John Wick', 3, 4),
      p('Guardians of the Galaxy', 3, 4),
    ],
  },
  {
    slug: 'tv_shows',
    name: 'TV Shows',
    description: 'Widely watched television series.',
    prompts: [
      p('Friends', 2, 5),
      p('Game of Thrones', 2, 5, 'GoT'),
      p('Breaking Bad', 2, 5),
      p('The Office', 2, 5),
      p('Stranger Things', 2, 5),
      p('The Simpsons', 1, 5, 'Simpsons'),
      p('SpongeBob SquarePants', 2, 5, 'SpongeBob'),
      p('The Walking Dead', 3, 4),
      p('Sherlock', 3, 4),
      p('Squid Game', 2, 5),
      p('The Mandalorian', 3, 4),
      p('Wednesday', 3, 4),
      p('Peaky Blinders', 3, 4),
      p('The Crown', 3, 4),
      p('Black Mirror', 3, 4),
      p('Seinfeld', 3, 4),
      p('The Big Bang Theory', 2, 5),
      p('Lost', 3, 4),
      p('Doctor Who', 3, 4),
      p('The Witcher', 3, 4),
      p('Money Heist', 3, 4, 'La Casa de Papel'),
      p('Ted Lasso', 3, 4),
      p('The Sopranos', 3, 4),
      p('Better Call Saul', 3, 4),
      p('Westworld', 4, 3),
      p('Narcos', 3, 4),
      p('Vikings', 3, 4),
      p('House of the Dragon', 3, 4),
      p('Euphoria', 3, 4),
      p('Bridgerton', 3, 4),
      p("Grey's Anatomy", 3, 4),
      p('House', 3, 4, 'House MD'),
      p('How I Met Your Mother', 3, 4, 'HIMYM'),
      p('Modern Family', 3, 4),
      p('Parks and Recreation', 3, 4, 'Parks and Rec'),
      p('Brooklyn Nine-Nine', 3, 4, 'Brooklyn 99'),
      p('Rick and Morty', 2, 5),
      p('Family Guy', 2, 5),
      p('South Park', 2, 5),
      p('Futurama', 3, 4),
      p('Avatar The Last Airbender', 3, 4),
      p('Dragon Ball Z', 3, 4, 'DBZ'),
      p('Naruto', 3, 4),
      p('Scooby-Doo', 2, 5, 'Scooby Doo'),
      p('Tom and Jerry', 2, 5),
      p('Star Trek', 3, 4),
      p('The X-Files', 3, 4, 'X-Files'),
      p('Dexter', 3, 4),
      p('Prison Break', 3, 4),
      p('Gossip Girl', 3, 4),
      p('Downton Abbey', 3, 4),
    ],
  },
  {
    slug: 'video_games',
    name: 'Video Games',
    description: 'Iconic games and franchises.',
    prompts: [
      p('Minecraft', 1, 5),
      p('Super Mario Bros', 2, 5, 'Super Mario'),
      p('Pac-Man', 1, 5, 'Pacman'),
      p('Tetris', 1, 5),
      p('The Legend of Zelda', 3, 4, 'Zelda'),
      p('Angry Birds', 2, 4),
      p('Among Us', 2, 4),
      p('Fortnite', 1, 5),
      p('Call of Duty', 2, 5, 'COD'),
      p('Pokémon', 1, 5, 'Pokemon'),
      p('Grand Theft Auto', 2, 5, 'GTA'),
      p('The Sims', 2, 4),
      p('Sonic the Hedgehog', 2, 5, 'Sonic'),
      p('Halo', 3, 4),
      p('Mortal Kombat', 3, 4),
      p('Street Fighter', 3, 4),
      p('Animal Crossing', 3, 4),
      p('Candy Crush', 2, 4),
      p('Donkey Kong', 2, 4),
      p('Space Invaders', 3, 4),
      p('Roblox', 1, 5),
      p('Cyberpunk 2077', 4, 3, 'Cyberpunk'),
      p('Fall Guys', 2, 4),
      p('Overwatch', 3, 4),
      p('League of Legends', 2, 5, 'LoL'),
      p('Counter-Strike', 3, 4, 'CS', 'CSGO'),
      p('Valorant', 2, 4),
      p('Apex Legends', 3, 4, 'Apex'),
      p('World of Warcraft', 3, 4, 'WoW'),
      p('Final Fantasy', 3, 4),
      p('Resident Evil', 3, 4),
      p('Tomb Raider', 3, 4),
      p("Assassin's Creed", 3, 4),
      p('Red Dead Redemption', 3, 4),
      p('God of War', 3, 4),
      p('The Last of Us', 3, 4),
      p('Uncharted', 3, 4),
      p('FIFA', 2, 5),
      p('Guitar Hero', 3, 4),
      p('Just Dance', 3, 4),
      p('Mario Kart', 2, 5),
      p('Super Smash Bros', 2, 4, 'Smash Bros'),
      p('Metroid', 3, 4),
      p('Kirby', 3, 4),
      p('Splatoon', 3, 4),
      p('Portal', 3, 4),
      p('Skyrim', 3, 4),
      p('Fallout', 3, 4),
      p('Stardew Valley', 3, 4),
      p('Subway Surfers', 2, 4),
      p('Plants vs Zombies', 3, 4),
      p('Clash of Clans', 3, 4),
    ],
  },
  {
    slug: 'music_artists',
    name: 'Music Artists',
    description: 'Globally famous musicians and bands.',
    prompts: [
      p('Taylor Swift', 2, 5),
      p('Beyoncé', 2, 5, 'Beyonce'),
      p('Michael Jackson', 2, 5, 'MJ'),
      p('Elvis Presley', 3, 4, 'Elvis'),
      p('The Beatles', 2, 5, 'Beatles'),
      p('Eminem', 2, 5),
      p('Drake', 2, 5),
      p('Madonna', 3, 4),
      p('Lady Gaga', 2, 5),
      p('Adele', 2, 5),
      p('Ed Sheeran', 2, 5),
      p('Rihanna', 2, 5),
      p('Bruno Mars', 3, 4),
      p('Queen', 3, 4),
      p('Bob Marley', 3, 4),
      p('Justin Bieber', 2, 5),
      p('Ariana Grande', 2, 5),
      p('Billie Eilish', 2, 5),
      p('Snoop Dogg', 3, 4),
      p('Elton John', 3, 4),
      p('BTS', 2, 5),
      p('Coldplay', 3, 4),
      p('David Bowie', 3, 4),
      p('Prince', 3, 4),
      p('Whitney Houston', 3, 4),
      p('Mariah Carey', 3, 4),
      p('Frank Sinatra', 3, 4),
      p('The Rolling Stones', 3, 4, 'Rolling Stones'),
      p('Led Zeppelin', 3, 4),
      p('Pink Floyd', 3, 4),
      p('Nirvana', 3, 4),
      p('Metallica', 3, 4),
      p('U2', 3, 4),
      p('Imagine Dragons', 3, 4),
      p('Maroon 5', 3, 4),
      p('The Weeknd', 2, 5),
      p('Post Malone', 2, 5),
      p('Kendrick Lamar', 3, 4),
      p('Kanye West', 2, 5, 'Ye'),
      p('Jay-Z', 3, 4),
      p('Nicki Minaj', 2, 5),
      p('Dua Lipa', 2, 5),
      p('Katy Perry', 2, 5),
      p('Shakira', 3, 4),
      p('Daft Punk', 3, 4),
      p('Harry Styles', 2, 5),
      p('Miley Cyrus', 2, 5),
      p('Olivia Rodrigo', 2, 5),
      p('Bad Bunny', 2, 5),
      p('ABBA', 3, 4),
      p('Spice Girls', 3, 4),
      p('One Direction', 2, 5),
    ],
  },
  {
    slug: 'books',
    name: 'Books',
    description: 'Famous novels and stories.',
    prompts: [
      p('Harry Potter', 1, 5),
      p('The Lord of the Rings', 2, 5, 'Lord of the Rings', 'LOTR'),
      p('The Hobbit', 3, 4, 'Hobbit'),
      p('Romeo and Juliet', 2, 5),
      p('Pride and Prejudice', 3, 4),
      p('Moby Dick', 3, 4),
      p('The Great Gatsby', 3, 4, 'Great Gatsby'),
      p('To Kill a Mockingbird', 3, 4),
      p('1984', 3, 4),
      p('The Hunger Games', 2, 5, 'Hunger Games'),
      p('Alice in Wonderland', 2, 5),
      p('Dracula', 2, 4),
      p('Frankenstein', 2, 4),
      p('The Cat in the Hat', 3, 4),
      p("Charlotte's Web", 3, 4),
      p('Treasure Island', 3, 4),
      p('The Da Vinci Code', 3, 4),
      p('Peter Pan', 2, 5),
      p('The Chronicles of Narnia', 3, 4, 'Narnia'),
      p('Charlie and the Chocolate Factory', 3, 4),
      p('Winnie the Pooh', 2, 5),
      p('Hamlet', 3, 4),
      p('Macbeth', 3, 4),
      p('The Odyssey', 3, 4),
      p('Lord of the Flies', 3, 4),
      p('The Catcher in the Rye', 3, 4),
      p('Of Mice and Men', 3, 4),
      p('Animal Farm', 3, 4),
      p('Brave New World', 3, 4),
      p('Fahrenheit 451', 3, 4),
      p('Little Women', 3, 4),
      p('Jane Eyre', 3, 4),
      p('Great Expectations', 3, 4),
      p('Oliver Twist', 3, 4),
      p('A Christmas Carol', 2, 5),
      p('The Jungle Book', 2, 5),
      p('The Secret Garden', 3, 4),
      p('Matilda', 2, 5),
      p('The BFG', 3, 4),
      p('James and the Giant Peach', 3, 4),
      p('Goosebumps', 3, 4),
      p('Diary of a Wimpy Kid', 2, 5),
      p('Percy Jackson', 3, 4),
      p('The Maze Runner', 3, 4),
      p('Divergent', 3, 4),
      p('Twilight', 2, 5),
      p('The Fault in Our Stars', 3, 4),
      p('Gone Girl', 3, 4),
      p('Dune', 3, 4),
      p('The Little Prince', 3, 4),
      p('The Alchemist', 3, 4),
    ],
  },
  {
    slug: 'landmarks',
    name: 'Landmarks',
    description: 'Famous places and monuments around the world.',
    prompts: [
      p('Eiffel Tower', 2, 5),
      p('Big Ben', 2, 5),
      p('The Colosseum', 3, 4, 'Colosseum'),
      p('Taj Mahal', 2, 5),
      p('Great Wall of China', 2, 5, 'Great Wall'),
      p('Pyramids of Giza', 3, 4, 'The Pyramids', 'Pyramids'),
      p('Golden Gate Bridge', 3, 4),
      p('Leaning Tower of Pisa', 3, 4, 'Tower of Pisa'),
      p('Christ the Redeemer', 4, 3),
      p('Stonehenge', 3, 4),
      p('Mount Rushmore', 3, 4),
      p('Sydney Opera House', 3, 4),
      p('Niagara Falls', 3, 4),
      p('The Grand Canyon', 2, 5, 'Grand Canyon'),
      p('Buckingham Palace', 3, 4),
      p('The White House', 2, 5, 'White House'),
      p('Times Square', 3, 4),
      p('Mount Everest', 2, 5, 'Everest'),
      p('Machu Picchu', 3, 4),
      p('Burj Khalifa', 4, 3),
      p('The Sphinx', 3, 4, 'Sphinx'),
      p('The Parthenon', 3, 4, 'Parthenon', 'Acropolis'),
      p('The Brandenburg Gate', 4, 3, 'Brandenburg Gate'),
      p('The Berlin Wall', 3, 4, 'Berlin Wall'),
      p('Sagrada Familia', 4, 3),
      p('The Louvre', 3, 4, 'Louvre'),
      p('Notre Dame', 3, 4),
      p('Arc de Triomphe', 3, 4),
      p('The Sistine Chapel', 3, 4, 'Sistine Chapel'),
      p('The Tower of London', 3, 4, 'Tower of London'),
      p('Tower Bridge', 3, 4),
      p('The London Eye', 3, 4, 'London Eye'),
      p('Neuschwanstein Castle', 4, 3),
      p('The Hollywood Sign', 3, 4, 'Hollywood Sign'),
      p('The Empire State Building', 2, 5, 'Empire State Building'),
      p('Brooklyn Bridge', 3, 4),
      p('Mount Kilimanjaro', 3, 4, 'Kilimanjaro'),
      p('Victoria Falls', 3, 4),
      p('The Great Barrier Reef', 3, 4, 'Great Barrier Reef'),
      p('Uluru', 4, 3, 'Ayers Rock'),
      p('The Forbidden City', 4, 3, 'Forbidden City'),
      p('The Terracotta Army', 4, 3, 'Terracotta Army'),
      p('Angkor Wat', 4, 3),
      p('Petra', 4, 3),
      p('Chichen Itza', 4, 3),
      p('The Hoover Dam', 3, 4, 'Hoover Dam'),
      p('The Lincoln Memorial', 3, 4, 'Lincoln Memorial'),
      p('Central Park', 3, 4),
      p('The Sahara Desert', 3, 4, 'Sahara'),
      p('The Amazon Rainforest', 3, 4, 'Amazon Rainforest'),
    ],
  },
];
